spring:
  application:
   name: ngo
  config:
    import: "optional:file:.env[.properties]"

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: validate

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 # was 300 = 5m
    refreshTokenExpiration: 604800 # 7d

  flyway:
    enabled: true
    locations: classpath:db/migration


