spring:
  datasource:
    url:
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
websiteUrl: http://localhost:4242


